# Generated by Django 5.2 on 2025-06-18 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curriculums.ciudad')),
            ],
        ),
    ]
